epochs : 50
lr : 1e-3
batch_size : 1
train_val_ratio : 0.8
input_data_path : './data/datasets/iq/qam1024_5000x20/5000_samples_mu=0.008'
output_model_path : './data/saved_models/iq'
device : 'cuda'
models: '
{
  "n_layers": 5,
  "activation_name": "PReLU"
};{
  "n_layers": 10,
  "activation_name": "PReLU"
};{
  "n_layers": 20,
  "activation_name": "PReLU"
}'
