epochs : 50
lr : 1e-3
batch_size : 1
train_val_ratio : 0.8
input_data_path : './data/datasets/spectrum/qam1024_5001x20/5001_samples_mu=0.008'
output_model_path : './data/saved_models'
device : 'cuda'
models: '
{
  "n_layers": 30,
  "activation_name": "PReLU"
}'
