mu_start: 1e-2
mu_end: 1e7
num_of_mu: 30
mu_scale: 'log'
n_realisation: 10
is_print: false
is_plot: false
is_save: true
channel_config:
  # System Configuration:
  W: 0.05               # Total bandwidth, estimated [THz]
  Nspans: 12            # The number of spans
  span_length: 80       # Transmission span [km]
  M_QAM: 16             # QAM order (2,4,16,64,256)
  Ts: 1                 # Symbol period [??]

  # Modulation and Coding:
  Nos: 16               # Oversampling factor (must be even)
  eta: 2                # spectral efficiency penalty factor (1,4]
  mu: 0.1               # Dimensionless power scaling factor (RRC) <- this one is redundant (D/C)
  bet: 0.2              # roll-off factor
  with_ssf: True        # whether to use SSF or not
  with_noise: True      # whether to add noise or not

  # Fiber and Dispersion:
  alphadB: 0.2          # Power loss db/km
  beta2: -21            # ps^2/km
  gamma: 1.27           # Nonlinear coefficient in [1/km*W]
  dz: 0.2               # Z-step, [km] - initial step estimate