model_path: 'data/prod_models/mu-0.125__8000ds__UnetWithSkips__51epochs'
ds_init_path: './data/datasets/qam16_5000x50/'
train_ds_ratio: 0.0
val_ds_ratio: 0.0
test_ds_ratio: 1
wandb_project: 'models_v3' 
run_name: 'skip_connection_ultra_wide_ds'
