lr: 1e-3  
min_lr: 1e-5
epochs: 51
batch_size: 1 
train_ds_ratio: 0.05 
val_ds_ratio: 0.03
input_data_path: './data/datasets/qam16_100000x20/100000_samples_mu=0.125' 
output_model_path: './data/prod_models' 
device: 'cuda'
wandb_project: 'models_v2' 
model_name: "unet_with_skips"  # name of the run in wandb
ds_limit: 0
model_class: "UnetWithSkips" 
is_analyze_after: false
verbose: true