epochs: 15
lr: 1e-3
batch_size: 1
train_val_ratio: 0.8
input_data_path: './data/datasets/spectrum/qam1024_160x20/160_samples_mu=0.008'
output_model_path: './data/saved_models'
device: 'cuda'
wandb_project: 'thesis_model_scan_test'
run_name: "test_paper2"  # name of the run in wandb
