lr: 1e-3  # learning rate
epochs: 3  # num of epochs
batch_size: 1  # batch size
train_val_ratio: 0.8  # train vs val ratio
input_data_path: './data/datasets/qam1024_160x20/160_samples_mu=0.008'  # path to data
output_model_path: './data/test_models'  # path to save model
device: 'cpu'  # device to use
wandb_project: 'thesis_model_scan_test'  # wandb project name
run_name: "test_model_10epochs"  # name of the run in wandb