epochs: 1  # num of epochs
lr: 1e-3  # learning rate
batch_size: 1  # batch size
train_val_ratio: 0.8  # train vs val ratio
ds_limit: 3
input_data_path: './data/datasets/qam1024_160x20/160_samples_mu=0.008'  # path to data
output_model_path: './data/test_models'  # path to save model
device: 'cpu'  # device to use
wandb_project: 'Thesis_model_scanning_test'
model_name: "test_paper1"  # name of the run in wandb
model_class: "Paper1Model"