lr: 1e-3  
min_lr: 1e-5
epochs: 5
batch_size: 1 
train_ds_ratio: 0.5 
val_ds_ratio: 0.25
test_ds_ratio: 0.25
input_data_path: '/data/yarcoh/thesis_data/data/datasets/c/noiseless_big/30000samples_20mu/mu=0.19' 
output_model_path: '/data/yarcoh/thesis_data/data/test_models' 
device: 'cuda'
wandb_project: 'models_v4_debug' 
model_name: "unet_v2_channel2_noiseless_c_big_ds_mu019"  # name of the run in wandb
ds_limit: 0
model_class: "UnetWithSkips" 
is_analyze_after: true
verbose: true