lr: 1e-3  
min_lr: 1e-5
lambda_reg: 0  # regularization lambda (0 for no regularization)
epochs: 10
batch_size: 1 
train_ds_ratio: 0.5 
val_ds_ratio: 0.25
test_ds_ratio: 0.25
input_data_path: '/data/yarcoh/thesis_data/data/datasets/b1/noiseless/1000samples_20mu/mu=0.43' 
output_model_path: '/data/yarcoh/thesis_data/data/test_models' 
device: 'cuda'
wandb_project: 'models_v4_debug' 
model_name: "unet_v4_noiseless_b1_mu043_noreg"  # name of the run in wandb
ds_limit: 0
model_class: "UnetV4Simple" 
is_analyze_after: true
verbose: true