data_len: 10  # for each mu
mu_len: 20
num_symbols: 64
qam: 16
logger_path: './logs'
output_path: './data/datasets/spectrum'
max_workers: 64
data_type: 0
mu_start: 0.00005
mu_end: 0.3
is_analyze_after: true