data_len: 8  # for each mu
mu_len: 11
num_symbols: 64
qam: 16
logger_path: './logs'
output_path: './data/datasets/spectrum'
max_workers: 10
data_type: 0
mu_start: 0.0001
over_sampling: 8
mu_end: 0.01
is_analyze_after: true