data_len: 8  # for each mu
mu_len: 11
num_symbols: 512
qam: 256
logger_path: './logs'
output_path: './data/datasets/iq'
max_workers: 10
data_type: 1
mu_start: 0.0001
mu_end: 0.01
is_analyze_after: true