num_samples: 1000  # for each mu
num_mus: 20
mu_start: 0.1
mu_end: 1
logger_path: './logs'
output_path: '/data/yarcoh/thesis_data/data/datasets/b/noiseless'
to_collect_ber: True


channel_config:
  # System Configuration:
  W: 0.05               # Total bandwidth, estimated [THz]
  Nspans: 12            # The number of spans
  La: 80                # Transmission span [km]
  M_QAM: 16             # QAM order (2,4,16,64,256)
  Ts: 1                 # Symbol period [??]

  # Modulation and Coding:
  Nos: 16               # Oversampling factor (must be even)
  eta: 2                # spectral efficiency penalty factor (1,4]
  mu: 0.15              # Dimensionless power scaling factor (RRC) <- this one is redundant (D/C)
  bet: 0.2              # roll-off factor
  with_ssf: True        # whether to use SSF or not
  with_noise: False     # whether to add noise or not

  # Fiber and Dispersion:
  beta2: -21            # ps^2/km
  gamma: 1.27           # Nonlinear coefficient in [1/km*W]
  dz: 0.2               # Z-step, [km] - initial step estimate
  K_T: 1.13
  chi: 0.0461
  io_type: 'b'